name: Run Service
on: [push]

jobs:
  run-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
      - name: Build
        run: dotnet build src/SystemObserver.sln --configuration Release
      - name: Run
        run: |
          # Запуск в фоновом режиме на 10 секунд для проверки старта
          timeout 10s dotnet run --project src/SystemObserver.Worker/SystemObserver.Worker.csproj --configuration Release || [ $? -eq 124 ]
